# Site settings
title: Caleb Logan
description: Caleb Logans portfolio
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://caleblogan.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Caleb Logan
user_description: I am a web developer focusing on front-end react development. I can write backend code and like working with restful apis. I am adaptable and I'm comfortable with learning new languages and working in environments other than web development.
user_title: Software Developer
email: clogan202@gmail.com
twitter_username: lorem_ipsum
github_username:  caleblogan
linkedin_url: https://www.linkedin.com/in/caleb-logan-26075877/
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
