# Site settings
title: Caleb Logan
description: Caleb Logans portfolio
# Prod
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.caleblogan.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# Local / Dev
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Caleb Logan
user_description: I am a software engineer focusing on web development. I'm adaptable and comfortable with learning new languages and working in environments other than web development. I enjoy building restful apis and building ui with react.
user_title: Software Engineer
email: clogan202@gmail.com
twitter_username: lorem_ipsum
github_username:  caleblogan
linkedin_url: https://www.linkedin.com/in/caleb-logan-26075877/
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-33448221-6"

exclude: ['package.json', 'src' , 'node_modules']
